services:
  app:
    build:
      context: .
    ports:
      - "3000:3000" # Assurez-vous que le format est bien "hôte:conteneur"
    env_file:
      - .env.local
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_project
    ports:
      - "3306:3306" # Format correct pour exposer le port MySQL

